### ISSUE TITLE
xcrash  : NativeHandler System.loadLibrary failed

### ISSUE THREAD

**Issue by superoidlau** [iqiyi/xCrash#111]
hello, error happened on some mobiles.
reason: loadLibrary fail.

`XCrashTracker: XCrashTracker initialize: ROM{name='MIUI' versionCode=0  versionName='null' ma=xiaomi' manufacturer=Xiaomi'}
06-21 17:53:44.676 10619 10701 E xcrash  : NativeHandler System.loadLibrary failed
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar"  zip file "/system/framework/android.test.runner.jar"  zip file "/system/framework/android.test.mock.jar"  zip file "/data/app/com.*****-95WT4NFAvJFmoksX8Qb4Gg==/base.apk"] nativeLibraryDirectories=[/data/app/com.*****-95WT4NFAvJFmoksX8Qb4Gg==/lib/arm  /data/app/com.*****-95WT4NFAvJFmoksX8Qb4Gg==/base.apk!/lib/armeabi  /system/lib  /system/lib/arm  /system/lib/arm/nb]]] couldn't find "libxcrash.so"
	at java.lang.Runtime.loadLibrary0(Runtime.java:1090)
	at java.lang.System.loadLibrary(System.java:1669)
	at xcrash.NativeHandler.initialize(NativeHandler.java:85)
	at xcrash.XCrash.init(XCrash.java:188)`

Device info:
Mi Note 3   os version：6.0.1

**Comment by superoidlau** [comment]
but, this error is not necessary. sometimes native crash can be collected. (⊙︿⊙)

**Comment by superoidlau** [comment]
loadLibrary failed on this development board as well.
deviceName: ZC-328   os version: 7.1.2
CPU
RK3288，4核Cortex-A17架构，主频2.0G

http://www.ds-360.com/product/doc/266211.htm
