### ISSUE TITLE
同一版本xCrash，国外环境收集的native crash中不含java 堆栈信息java stacktrace:   (no managed stack frames)，国内采集的却包含，这是什么原因呢？

### ISSUE THREAD

**Issue by lanlianhuashi** [iqiyi/xCrash#57]
=======================国外不含java stacktrace的native堆栈信息如下：=================================
dump status:
child terminated normally with non-zero exit status(102)

*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Start time: '2020-11-18T01:56:33.073-0300'
Crash time: '2020-11-18T02:07:15.837-0300'
App ID: 'com.taxis99'
App version: '6.15.8'
Rooted: 'No'
API level: '25'
OS version: '7.1.1'
Kernel version: 'Linux version 3.18.31-15630411 #1 SMP PREEMPT Tue Oct 15 04:26:46 KST 2019 (armv7l)'
ABI list: 'armeabi-v7a,armeabi'
Manufacturer: 'samsung'
Brand: 'samsung'
Model: 'SM-J250M'
Build fingerprint: 'samsung/j2y18lteub/j2y18lte:7.1.1/NMF26X/J250MUBS5ASJD:user/release-keys'
ABI: 'arm'
pid: 505, tid: 2723, name: Chrome_InProcGp  >>> com.taxis99 <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x8
    r0  00000000  r1  00000001  r2  00000000  r3  00000000
    r4  6d032ee0  r5  0c649e80  r6  0c649e84  r7  00000000
    r8  6cb9ce18  r9  6cb9ce14  r10 6cb9ce24  r11 00000000
    ip  91430320  sp  6192d630  lr  8f9bc5b3  pc  906fb5b4

backtrace:
    #00 pc 027875b4  /data/app/com.android.chrome-2/base.apk!/lib/armeabi-v7a/libmonochrome.so

java stacktrace:
  (no managed stack frames)

memory info:
 System Summary (From: /proc/meminfo)
  MemTotal:        1375908 kB
  MemFree:          109036 kB
  MemAvailable:     286336 kB
  Buffers:            5380 kB
  Cached:           183104 kB
  SwapCached:         4656 kB
  Active:           225256 kB
  Inactive:         230340 kB
  Active(anon):     128144 kB
  Inactive(anon):   141008 kB
  Active(file):      97112 kB
  Inactive(file):    89332 kB
  Unevictable:         576 kB
  Mlocked:             576 kB
  HighTotal:        929792 kB
  HighFree:          91528 kB
  LowTotal:         446116 kB
  LowFree:           17508 kB
  SwapTotal:       1048572 kB
  SwapFree:          66384 kB
  Dirty:               484 kB
  Writeback:             0 kB
  AnonPages:        267604 kB
  Mapped:           268816 kB
  Shmem:              2040 kB
  Slab:             110004 kB
  SReclaimable:      23568 kB
  SUnreclaim:        86436 kB
  KernelStack:       18336 kB
  PageTables:        44868 kB
  NFS_Unstable:          0 kB
  Bounce:                0 kB
  WritebackTmp:          0 kB
  CommitLimit:     1736524 kB
  Committed_AS:   51447572 kB
  VmallocTotal:     385024 kB
  VmallocUsed:      132088 kB
  VmallocChunk:     130724 kB
-
 Process Status (From: /proc/PID/status)
  Name:	com.taxis99
  State:	S (sleeping)
  Tgid:	505
  Ngid:	0
  Pid:	505
  PPid:	524
  TracerPid:	0
  Uid:	10196	10196	10196	10196
  Gid:	10196	10196	10196	10196
  FDSize:	1024
  Groups:	3001 3002 3003 9997 50196
  VmPeak:	 2731860 kB
  VmSize:	 2688672 kB
  VmLck:	       0 kB
  VmPin:	       0 kB
  VmHWM:	  305672 kB
  VmRSS:	  252168 kB
  VmData:	  375564 kB
  VmStk:	    8192 kB
  VmExe:	      52 kB
  VmLib:	  215640 kB
  VmPTE:	    1270 kB
  VmSwap:	   87464 kB
  Threads:	160
  SigQ:	1/9507
  SigPnd:	0000000000000000
  ShdPnd:	0000000000000000
  SigBlk:	0000000000001200
  SigIgn:	0000000000000000
  SigCgt:	20000002000084fc
  CapInh:	0000000000000000
  CapPrm:	0000000000000000
  CapEff:	0000000000000000
  CapBnd:	0000000000000000
  Seccomp:	0
  Cpus_allowed:	f
  Cpus_allowed_list:	0-3
  voluntary_ctxt_switches:	103244
  nonvoluntary_ctxt_switches:	42089
-
 Process Limits (From: /proc/PID/limits)
  Limit                     Soft Limit           Hard Limit           Units
  Max cpu time              unlimited            unlimited            seconds
  Max file size             unlimited            unlimited            bytes
  Max data size             unlimited            unlimited            bytes
  Max stack size            8388608              unlimited            bytes
  Max core file size        0                    unlimited            bytes
  Max resident set          unlimited            unlimited            bytes
  Max processes             9507                 9507                 processes
  Max open files            4096                 4096                 files
  Max locked memory         67108864             67108864             bytes
  Max address space         unlimited            unlimited            bytes
  Max file locks            unlimited            unlimited            locks
  Max pending signals       9507                 9507                 signals
  Max msgqueue size         819200               819200               bytes
  Max nice priority         40                   40
  Max realtime priority     0                    0
  Max realtime timeout      unlimited            unlimited            us
-
 Process Details (From: /proc/PID/smaps)
                   Pss      Pss   Shared  Private   Shared  Private  SwapPss
                 Total    Clean    Dirty    Dirty    Clean    Clean    Dirty
                ------   ------   ------   ------   ------   ------   ------
  Native Heap    18477        0       20    18472       84        0    21857
  Dalvik Heap    17245        0       16    17236      184        0    25358
 Dalvik Other     4416        0        0     4416       32        0     5990
        Stack     1172        0        0     1172        0        0     1348
       Ashmem      804        0       20      800        0        0        0
      Gfx dev   148358        0       92   148312        0        0        0
    Other dev       23        0      116        0        0       20        0
     .so mmap     3920     2824      104      256     8856     2824      391
    .jar mmap        8        8        0        0        0        8        0
    .apk mmap    12048    10168        0       60     7376    10168       92
    .ttf mmap        7        0        0        0       24        0        0
    .dex mmap     2946     2616        0       40      876     2616        0
    .oat mmap     1566      528        0        0    11276      528        0
    .art mmap     1324      108      468      932     6372      108     1381
   Other mmap      777        0        0        8      504      652        0
      Unknown    12096        0       12    12036        8       60    20799
        TOTAL   302403    16252      848   203740    35592    16984    77216
-
 Process Dalvik Details (From: /proc/PID/smaps)
        .Heap    17040        0        0    17040        0        0    11436
         .LOS        8        0        0        8        4        0    13093
      .Zygote      153        0       16      144      180        0      249
   .NonMoving       44        0        0       44        0        0      580
 .LinearAlloc     1316        0        0     1316        0        0     4386
          .GC     1684        0        0     1684       32        0      600
    .JITCache      984        0        0      984        0        0      936
 .IndirectRef      432        0        0      432        0        0       68
     .App dex     2946     2616        0       40      876     2616        0
     .App art        4        4        0        0        0        4        0
    .Boot art     1320      104      468      932     6372      104     1381
-
 Process Summary (From: /proc/PID/smaps)
                       Pss(KB)
                        ------
           Java Heap:    18276
         Native Heap:    18472
                Code:    16500
               Stack:     1172
       Private Other:   166304
              System:    81679
               TOTAL:   302403       TOTAL SWAP PSS:    77216
-

memory info:
 Process Summary (From: android.os.Debug.MemoryInfo)
                       Pss(KB)
                        ------
           Java Heap:    18360
         Native Heap:    18456
                Code:    16664
               Stack:     1184
            Graphics:   148312
       Private Other:    18056
              System:    81569
               TOTAL:   302601           TOTAL SWAP:    86936
foreground:
yes

================================国内的含java stacktrace如下：===============================
dump status:
child terminated normally with non-zero exit status(102)

*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Start time: '2020-11-18T15:43:39.383+0800'
Crash time: '2020-11-18T15:46:49.049+0800'
App ID: 'com.xx.sdu'
App version: '6.0.17'
Rooted: 'No'
API level: '29'
OS version: '10'
Kernel version: 'Linux version 4.14.141-perf-g52ed0e6 #1 SMP PREEMPT Tue Sep 22 17:22:11 CST 2020 (armv8l)'
ABI list: 'arm64-v8a,armeabi-v7a,armeabi'
Manufacturer: 'Xiaomi'
Brand: 'Redmi'
Model: 'M2004J19C'
Build fingerprint: 'Redmi/lancelot/lancelot:10/QP1A.190711.020/V12.0.4.0.QJCCNXM:user/release-keys'
ABI: 'arm'
pid: 30918, tid: 30918, name: xx.sdu  >>> com.xx.sdu <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x14
    r0  00000014  r1  00000000  r2  00000000  r3  00000000
    r4  00000014  r5  ffba1a18  r6  00000000  r7  00000000
    r8  00000001  r9  ea55ce00  r10 ea52d440  r11 00000000
    ip  e79a44ac  sp  ffba19f0  lr  e798b02d  pc  e893ea0a

backtrace:
    #00 pc 000a6a0a  /apex/com.android.runtime/lib/bionic/libc.so (pthread_mutex_lock+5)
    #01 pc 0008802c  /system/lib/libgui.so (_ZNK7android14SurfaceControl9getHandleEv+15)
    #02 pc 000bf8fe  /system/lib/libandroid_runtime.so

java stacktrace:
  at android.view.SurfaceControl.nativeGetHandle(SurfaceControl.java)
  at android.view.SurfaceControl.getHandle(SurfaceControl.java:1178)
  at android.view.SurfaceControl$Transaction.setRelativeLayer(SurfaceControl.java:2442)
  at android.view.SurfaceControl.setRelativeLayer(SurfaceControl.java:1207)
  at android.view.SurfaceView.updateBackgroundVisibilityInTransaction(SurfaceView.java:592)
  at android.view.SurfaceView.updateSurface(SurfaceView.java:774)
  at android.view.SurfaceView.onWindowVisibilityChanged(SurfaceView.java:321)
  at android.view.View.dispatchWindowVisibilityChanged(View.java:13895)
  at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1606)
  at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1606)
  at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1606)
  ... repeated 5 times
  at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2229)
  at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1899)
  at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8060)
  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:969)
  at android.view.Choreographer.doCallbacks(Choreographer.java:793)
  at android.view.Choreographer.doFrame(Choreographer.java:728)
  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:954)
  at android.os.Handler.handleCallback(Handler.java:883)
  at android.os.Handler.dispatchMessage(Handler.java:100)
  at android.os.Looper.loop(Looper.java:224)
  at android.app.ActivityThread.main(ActivityThread.java:7561)
  at java.lang.reflect.Method.invoke(Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)

memory info:
 System Summary (From: /proc/meminfo)
  MemTotal:        3844668 kB
  MemFree:           69112 kB
  MemAvailable:     771852 kB
  Buffers:           18064 kB
  Cached:           945564 kB
  SwapCached:        30880 kB
  Active:          1299200 kB
  Inactive:         796204 kB
  Active(anon):    1010500 kB
  Inactive(anon):   318204 kB
  Active(file):     288700 kB
  Inactive(file):   478000 kB
  Unevictable:      163384 kB
  Mlocked:          163384 kB
  SwapTotal:       2113436 kB
  SwapFree:         351960 kB
  Dirty:               748 kB
  Writeback:             0 kB
  AnonPages:       1289312 kB
  Mapped:           692008 kB
  Shmem:             34568 kB
  Slab:             237808 kB
  SReclaimable:      57748 kB
  SUnreclaim:       180060 kB
  KernelStack:       72352 kB
  PageTables:       122020 kB
  NFS_Unstable:          0 kB
  Bounce:                0 kB
  WritebackTmp:          0 kB
  CommitLimit:     4035768 kB
  Committed_AS:   128332396 kB
  VmallocTotal:   263061440 kB
  VmallocUsed:           0 kB
  VmallocChunk:          0 kB
  CmaTotal:         344064 kB
  CmaFree:            1320 kB
-
 Process Status (From: /proc/PID/status)
  Name:	xx.sdu
  Umask:	0077
  State:	R (running)
  Tgid:	30918
  Ngid:	0
  Pid:	30918
  PPid:	495
  TracerPid:	0
  Uid:	10227	10227	10227	10227
  Gid:	10227	10227	10227	10227
  FDSize:	1024
  Groups:	3001 3002 3003 9997 20227 50227
  VmPeak:	 2863344 kB
  VmSize:	 2708020 kB
  VmLck:	       0 kB
  VmPin:	       0 kB
  VmHWM:	  432772 kB
  VmRSS:	  198700 kB
  RssAnon:	       0 kB
  RssFile:	  191532 kB
  RssShmem:	    7168 kB
  VmData:	 1559236 kB
  VmStk:	    8192 kB
  VmExe:	      20 kB
  VmLib:	  265968 kB
  VmPTE:	    2812 kB
  VmPMD:	      16 kB
  VmSwap:	   90008 kB
  Threads:	200
  SigQ:	1/12922
  SigPnd:	0000000000000000
  ShdPnd:	0000000000000000
  SigBlk:	00000000fffbfeff
  SigIgn:	0000000000000001
  SigCgt:	0000000e400084fc
  CapInh:	0000000000000000
  CapPrm:	0000000000000000
  CapEff:	0000000000000000
  CapBnd:	0000000000000000
  CapAmb:	0000000000000000
  NoNewPrivs:	0
  Seccomp:	2
  Speculation_Store_Bypass:	thread vulnerable
  Cpus_allowed:	ff
  Cpus_allowed_list:	0-7
  Mems_allowed:	1
  Mems_allowed_list:	0
  voluntary_ctxt_switches:	29937
  nonvoluntary_ctxt_switches:	10941
-
 Process Limits (From: /proc/PID/limits)
  Limit                     Soft Limit           Hard Limit           Units
  Max cpu time              unlimited            unlimited            seconds
  Max file size             unlimited            unlimited            bytes
  Max data size             unlimited            unlimited            bytes
  Max stack size            8388608              unlimited            bytes
  Max core file size        0                    unlimited            bytes
  Max resident set          unlimited            unlimited            bytes
  Max processes             12922                12922                processes
  Max open files            32768                32768                files
  Max locked memory         unlimited            unlimited            bytes
  Max address space         unlimited            unlimited            bytes
  Max file locks            unlimited            unlimited            locks
  Max pending signals       12922                12922                signals
  Max msgqueue size         819200               819200               bytes
  Max nice priority         40                   40
  Max realtime priority     0                    0
  Max realtime timeout      unlimited            unlimited            us
-
 Process Details (From: /proc/PID/smaps)
                   Pss      Pss   Shared  Private   Shared  Private  SwapPss
                 Total    Clean    Dirty    Dirty    Clean    Clean    Dirty
                ------   ------   ------   ------   ------   ------   ------
  Native Heap    59864        0      748    59740        0        0    63186
  Dalvik Heap        0        0        0        0        0        0        0
        Stack       48        0        4       48        0        0       40
       Ashmem     2172        0     1448     1584       12        0        0
    Other dev       29        0      292        0        0       28        0
     .so mmap    25132    18728      952     2304    20152    18728      400
    .jar mmap     2669      940        0        0    22380      940        0
    .apk mmap     6826     5144        0       28     6928     5144      124
    .ttf mmap     1082      184        0        0     2060      184        0
    .dex mmap    39590    39096        0      184     1040    39096      624
    .oat mmap     6028      500        0       84    48228      500        0
    .art mmap     2476       68    10632     1536      104       68       92
   Other mmap     8738        0     3364      932      780     6048        0
      Unknown    47646        0      636    47588        0        0    12350
        TOTAL   279116    64660    18076   114028   101684    70736    76816
-
 Process Dalvik Details (From: /proc/PID/smaps)
   .Boot vdex       72       72        0        0       12       72        0
     .App dex     2130     1716        0      184      788     1716      624
    .App vdex    37388    37308        0        0      240    37308        0
     .App art       68       68        0        0        0       68        0
    .Boot art     2408        0    10632     1536      104        0       92
-
 Process Summary (From: /proc/PID/smaps)
                       Pss(KB)
                        ------
           Java Heap:     1604
         Native Heap:    59740
                Code:    67192
               Stack:       48
       Private Other:    56180
              System:    94352
               TOTAL:   279116       TOTAL SWAP PSS:    76816
-

memory info:
 Process Summary (From: android.os.Debug.MemoryInfo)
                       Pss(KB)
                        ------
           Java Heap:    37652
         Native Heap:    59760
                Code:    67420
               Stack:       48
            Graphics:        0
       Private Other:    20232
              System:    94288
               TOTAL:   279400           TOTAL SWAP:    88272

foreground:
yes

**Comment by xuqnqn** [comment]
这个跟国外还是国内没关系的，有些native crash 就是没有Java 的堆栈信息

**Comment by lanlianhuashi** [comment]
> 这个跟国外还是国内没关系的，有些native crash 就是没有Java 的堆栈信息

方便告知一下什么情况下native crash 有Java 的堆栈信息，什么情况下没有且显示java stacktrace:
(no managed stack frames)

**Comment by xuqnqn** [comment]
如果当前崩溃的线程已经 attach 到了 jvm，那边就会有java stacktrace

**Comment by zwm11** [comment]
最后解决了吗？

**Comment by lanlianhuashi** [comment]
> 最后解决了吗？

没有

**Comment by lxs0226** [comment]
应该是native层自己create的线程崩溃了，这种是捕获不到java层的堆栈信息的，但如果是jni调用的native层当前线程崩溃了，是可以获取到堆栈信息的

**Comment by zhaoxiuyu** [comment]
请问你是用什么收集的

**Comment by Haoxiqiang** [comment]
It is a possibility that java's stacktrace may be swallowed by gms related components.

**Comment by Haoxiqiang** [comment]
just like:umeng or other crash analytic components
